services:
    cache:
      image: redis:alpine
      ports:
        - "6379:6379"
      volumes:
        - redis_vemeet_data:/data
      networks:
        - ve

networks:
  ve:

volumes:
  redis_vemeet_data:
