spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?user=${DB_USERNAME}&password=${DB_PASSWORD}&sslmode=require&connectTimeout=30
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
  data:
    redis:
      port: 6379
      host: localhost
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/${AWS_COGNITO_USER_POOL}
          jwk-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/${AWS_COGNITO_USER_POOL}/.well-known/jwks.json

  aws:
    cognito:
      region: eu-central-1
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
      userPoolId: ${AWS_COGNITO_USER_POOL}
      clientId: ${AWS_COGNITO_CLIENT_ID}
      clientSecret: ${AWS_COGNITO_SECRET}
      domain: ${AWS_COGNITO_DOMAIN}


server:
  port: 8080

# Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui