name: Backend Deployment
on:
  push:
    branches: [dev]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR repository
        id: create-ecr-repo
        run: |
          aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} || \
          aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY }}
        env:
          ECR_REPOSITORY: vemeet-backend

      - name: Build and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: vemeet-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building Docker image with Jib..."
          ./gradlew clean build jib \
            -Djib.to.image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -Djib.to.tags=latest \
            -Djib.to.auth.username=AWS \
            -Djib.to.auth.password=${{ steps.login-ecr.outputs.password }} \
            -Djib.container.jvmFlags="-Xms512m,-Xmx512m" \
            -Djib.container.ports=8080 \
            -Djib.container.mainClass=com.vemeet.backend.BackendApplicationKt

          echo "Pushed image with tag: $IMAGE_TAG"
          echo "Pushed image with tag: latest"

      - name: Verify image in ECR
        run: |
          aws ecr describe-images --repository-name ${{ env.ECR_REPOSITORY }} --image-ids imageTag=${{ github.sha }}
          aws ecr describe-images --repository-name ${{ env.ECR_REPOSITORY }} --image-ids imageTag=latest
        env:
          ECR_REPOSITORY: vemeet-backend